name: Publish Package
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x

      - name: Release Build
        run: dotnet build --configuration Release

      - name: Add GitHub Package Reference
        run: dotnet nuget add source --username korsarNek --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/korsarNek/index.json"

      - name: Add NuGet Package Reference
        run: dotnet nuget add source --name nuget "https://api.nuget.org/v3/index.json"

      - name: Publish NuGet Package
        run: |
          foreach($file in (Get-ChildItem "${{ github.workspace }}/Colipars/bin/Release" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --source github --skip-duplicate
            dotnet nuget push $file --source nuget --skip-duplicate --api-key "${{ secrets.NUGET_APIKEY }}"
          }